name: Workflow for Python using Snyk 
on: 
  pull_request:
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      id: snyk_step_id
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        command: |
          "pip3 install PyGithub"
          "python3 GithubTest.py"
      with:
        args: --summary
        # If you want to monitor a project after workflow runs:
        # command: monitor
    
    
      
    #- name: Create and issue
     # if: failure()
      #uses: maxkomarychev/oction-create-issue@v0.7.1
      #with:
       # token: ${{ secrets.GITHUB }}
        #title: a new test issue
        #body: here is the body of the issue
